# See the GitHub documentation for the supported funding platforms.
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

github: jdbruijn
