name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@v1.2.3
  run:
    uses: iterative/link-check/.github/workflows/link-check-deployment-status.yml@v0.13.0
